name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'Twrp_Device_Genter'
      IMG_URL:
        description: 'IMG_URL'
        required: true
        default: 'https://59-47-225-47.d.cjjd15.com:30443/download-cdn.123pan.cn/123-99/5cc26e9a/1813909630-0/5cc26e9aeeb13dba4a8db6067f48f063?v=5&t=1690873419&s=16908734198b4b1b79fc80c47d2f523a83f63d3467&r=ZTS2HD&filename=recovery.img&x-mf-biz-cid=d421a90c-feb1-45f6-a7e8-8b9f7cfbb3b7-a0d664&auto_redirect=0&xmfcid=219a9e62-573e-40a2-a0cd-b2255faac531-1-abf611255'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python python3 python3-pip python3-pip cpio wget
      
    - name: Set variables
      run: |
        echo "name=date::$(date +%F)" >> $GITHUB_OUTPUT
      id: var
      
    - name: Install TWRP generator 
      run: |
        pip3 install twrpdtgen
        mkdir dt
    
    - name: Download boot or recovery img
      run: |
        wget ${{ github.event.inputs.IMG_URL }}
        ls
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img

    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
